server:
  port: 8070
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: comment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recipeDB
      username: JavaUser
      password: root
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}
